//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: messagesSharp.proto
namespace Crypto.Utils
{
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"ECPointCoordinate")]
    public partial class ECPointCoordinate : global::ProtoBuf.IExtensible
    {
        public ECPointCoordinate() { }

        private int _k1;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"k1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public int k1
        {
            get { return _k1; }
            set { _k1 = value; }
        }
        private int _k2;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"k2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public int k2
        {
            get { return _k2; }
            set { _k2 = value; }
        }
        private int _k3;
        [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"k3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public int k3
        {
            get { return _k3; }
            set { _k3 = value; }
        }
        private int _m;
        [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name = @"m", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public int m
        {
            get { return _m; }
            set { _m = value; }
        }
        private byte[] _value;
        [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name = @"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public byte[] value
        {
            get { return _value; }
            set { _value = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"ECPublicKey")]
    public partial class ECPublicKey : global::ProtoBuf.IExtensible
    {
        public ECPublicKey() { }

        private ECPointCoordinate _x;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"x", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public ECPointCoordinate x
        {
            get { return _x; }
            set { _x = value; }
        }
        private ECPointCoordinate _y;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"y", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public ECPointCoordinate y
        {
            get { return _y; }
            set { _y = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"ECPrivateKey")]
    public partial class ECPrivateKey : global::ProtoBuf.IExtensible
    {
        public ECPrivateKey() { }

        private byte[] _D;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"D", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public byte[] D
        {
            get { return _D; }
            set { _D = value; }
        }

        private byte[] _passwordSalt = null;
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"passwordSalt", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public byte[] passwordSalt
        {
            get { return _passwordSalt; }
            set { _passwordSalt = value; }
        }

        private byte[] _encryptionSalt = null;
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"encryptionSalt", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public byte[] encryptionSalt
        {
            get { return _encryptionSalt; }
            set { _encryptionSalt = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"ECKey")]
    public partial class ECKey : global::ProtoBuf.IExtensible
    {
        public ECKey() { }

        private ECPublicKey _public;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"public", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public ECPublicKey @public
        {
            get { return _public; }
            set { _public = value; }
        }

        private ECPrivateKey _private = null;
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"private", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public ECPrivateKey @private
        {
            get { return _private; }
            set { _private = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"Signature")]
    public partial class Signature : global::ProtoBuf.IExtensible
    {
        public Signature() { }

        private byte[] _r;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"r", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public byte[] r
        {
            get { return _r; }
            set { _r = value; }
        }
        private byte[] _s;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"s", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public byte[] s
        {
            get { return _s; }
            set { _s = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

}