//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace fucdk
{
	/// <summary>
	/// Database       : RightPass
	/// Data Source    : d:\Coding\RightPass\DoneRightPass\DB\RightPass.sdf
	/// Server Version : 4.0.8876.1
	/// </summary>
	public partial class RightPassDB : LinqToDB.Data.DataConnection
	{
		public ITable<User> Users { get { return this.GetTable<User>(); } }

		public RightPassDB()
		{
		}

		public RightPassDB(string configuration)
			: base(configuration)
		{
		}
	}

	[Table("Users")]
	public partial class User
	{
		[PrimaryKey, NotNull    ] public int    ID           { get; set; } // int
		[Column,     NotNull    ] public string Name         { get; set; } // nvarchar(100)
		[Column,     NotNull    ] public byte[] PublicKey    { get; set; } // varbinary(1024)
		[Column,        Nullable] public byte[] PrivateKey   { get; set; } // varbinary(1024)
		[Column,        Nullable] public byte[] PrivateKeyIv { get; set; } // varbinary(16)
	}

	public static partial class tableExtensions
	{
		public static User Find(this ITable<User> table, int ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}
	}
}
